# Use the official ASP.NET Core runtime image
FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

# Use the SDK image to build the project
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["my-starter-svc/my-starter-svc.csproj", "my-starter-svc/"]
RUN dotnet restore "my-starter-svc/my-starter-svc.csproj"
COPY . .
WORKDIR "/src/my-starter-svc"
RUN dotnet build "my-starter-svc.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "my-starter-svc.csproj" -c Release -o /app/publish

# Final stage/image
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "my-starter-svc.dll"]
